### ISSUE TITLE
Add a README with examples of how to exercise the various DataTypes supported

### ISSUE THREAD

**Issue by comp615** [aarongustafson/WindowsShareTargetPWA#1]
It would be helpful if there was a README with details on how to test each type of data that can be shared on a basic version of windows. something like

**UrlLink**
Open Edge to your favorite webpage, and click the share button. This should include a title and the url.

**Files/StorageItems**
Create / download one (or more) file(s) with the extensions specified in your appxmanifest.xml file. Select them in explorer and right-click, select share.

**Bitmap**
???

**Text**
???

**Comment by aarongustafson** [comment]
Done. c10c2a9e0fe5ba5060df8d15ca6227ab97f256ac
